estimator:
  eval: |
    Pipeline([ ('cluster', NDGrid(min=-1.2, max=1.2, n_bins_per_feature=200)),
               ('msm', MaximumLikelihoodMSM(
                    lag=25,
                    score_method='vampe',
                    score_k=4))
              ])
  eval_scope: pyemma

strategy:
  name: gp
  params:
    seeds: 5
    kernels:
      - { name : GPy.kern.Matern52, params : {ARD : False}, options : {independent : True} }
      - { name : GPy.kern.White, params : {}, options : {independent : True} }
    acquisition: { name : ei, params : {} }

search_space:
  cluster__n_bins_per_feature:
    min: 10
    max: 1000
    type: int

cv:
  name: shufflesplit
  params:
    n_splits: 5
    test_size: 0.5

dataset_loader:
  name: numpy
  params:
    filenames: ../data/026.6pc/*.npy

trials:
    uri: sqlite:///osprey-trials.db
    project_name: k4
