estimator:
  eval: |
    Pipeline([ ('cluster', NDGrid(min=-1.2, max=1.2, n_bins_per_feature=200)),
               ('msm', MaximumLikelihoodMSM(
                    lag=3,
                    score_method='vampe',
                    score_k=3))
              ])
  eval_scope: pyemma

strategy:
  name: gp
  params:
    seeds: 10
    kernels:
      - { name : GPy.kern.Matern52, params : {ARD : False}, options : {independent : True} }
    acquisition: { name : ei, params : {} }

search_space:
  cluster__n_bins_per_feature:
    min: 20
    max: 1000
    type: int

cv:
  name: shufflesplit
  params:
    n_splits: 20
    test_size: 0.5

dataset_loader:
  name: numpy
  params:
    filenames: /mnt/storage/home/ra15808/hyperparamopt/QuadWell/data/100.0pc-128split/*.npy

trials:
    uri: sqlite:///osprey-trials.db
    project_name: k3
