"""Get sample data for testing and experimenting

msmbuilder autogenerated template version 2
created 2017-05-30T15:16:59.061464
please cite msmbuilder in any publications
"""
import os

from msmbuilder.example_datasets import FsPeptide

FsPeptide("./").cache()
if not os.path.exists("trajs"):
    os.symlink("fs_peptide", "trajs")
if not os.path.exists("top.pdb"):
    os.symlink("fs_peptide/fs-peptide.pdb", "top.pdb")
