estimator:
  pickle: model.pickl

strategy:
  name: grid

search_space:

  cluster__n_bins_per_feature:
    min: 10
    max: 500
    num: 50 
    var_type: int
    type: jump

  msm__score_k:
    min: 4
    max: 4
    num: 1
    var_type: int
    type: jump

  msm__lag:
    min: 1
    max: 1
    num: 1
    var_type: int
    type: jump
 
  msm__score_method:
    choices:
      - vamp2
    type: enum

cv:
  name: shufflesplit
  params:
    n_splits: 5
    test_size: 0.5

dataset_loader:
  name: numpy
  params:
    filenames: ../data/000.5pc-split/*.npy

trials:
    uri: sqlite:///osprey-trials.db
    project_name: split_5

